### ISSUE TITLE
Be more serious when you deal with your issues

### ISSUE THREAD

**Issue by mohanagy** [FACG2/webtopiaTodo#18]
[It's the break time (free time for eating).](https://github.com/FACG2/webtopiaTodo/issues/15#issuecomment-316609888)

**Comment by aajour** [comment]
![why](https://s-media-cache-ak0.pinimg.com/736x/0f/fd/27/0ffd27b099749bb56d8c26a21978b27f--joker-why-so-serious-why-so-serious-tattoo.jpg)

**Comment by aajour** [comment]
OK, sorry.
